/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

import com.gf.utils.PantallaInfo;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Angel
 */
public class PantallaDeCarga extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDeCarga2
     */
    public PantallaDeCarga() {
        initComponents();
        PantallaInfo.configPantalla(this);
        PantallaInfo.setPosicion(this);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(149, 181));
        jPanel1.setPreferredSize(new java.awt.Dimension(149, 181));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
