/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Ruben
 */
public class VistaQuienLoHizo extends javax.swing.JFrame {

    /**
     * Creates new form VistaQuienLoHizo
     */
    public VistaQuienLoHizo() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setSize(500, 500);
        this.setVisible(true);
    }

    public JLabel getjLabelImagen() {
        return jLabelImagen;
    }

    public void setjLabelImagen(JLabel jLabelImagen) {
        this.jLabelImagen = jLabelImagen;
    }

    public JLabel getjLabelPregunta() {
        return jLabelPregunta;
    }

    public void setjLabelPregunta(JLabel jLabelPregunta) {
        this.jLabelPregunta = jLabelPregunta;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanelBotones() {
        return jPanelBotones;
    }

    public void setjPanelBotones(JPanel jPanelBotones) {
        this.jPanelBotones = jPanelBotones;
    }

    public JPanel getjPanelImagen() {
        return jPanelImagen;
    }

    public void setjPanelImagen(JPanel jPanelImagen) {
        this.jPanelImagen = jPanelImagen;
    }

    public JPanel getjPanelPregunta() {
        return jPanelPregunta;
    }

    public void setjPanelPregunta(JPanel jPanelPregunta) {
        this.jPanelPregunta = jPanelPregunta;
    }

    public JPanel getjPanelPreguntaBotones() {
        return jPanelPreguntaBotones;
    }

    public void setjPanelPreguntaBotones(JPanel jPanelPreguntaBotones) {
        this.jPanelPreguntaBotones = jPanelPreguntaBotones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelImagen = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanelPreguntaBotones = new javax.swing.JPanel();
        jPanelPregunta = new javax.swing.JPanel();
        jLabelPregunta = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanelImagen.setMinimumSize(new java.awt.Dimension(300, 500));
        jPanelImagen.setPreferredSize(new java.awt.Dimension(300, 500));
        jPanelImagen.setLayout(new java.awt.BorderLayout());
        jPanelImagen.add(jLabelImagen, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelImagen);

        jPanelPreguntaBotones.setLayout(new javax.swing.BoxLayout(jPanelPreguntaBotones, javax.swing.BoxLayout.Y_AXIS));

        jPanelPregunta.setLayout(new javax.swing.BoxLayout(jPanelPregunta, javax.swing.BoxLayout.LINE_AXIS));

        jLabelPregunta.setText("¿Quien lo hizo?");
        jPanelPregunta.add(jLabelPregunta);

        jPanelPreguntaBotones.add(jPanelPregunta);

        jPanelBotones.setPreferredSize(new java.awt.Dimension(500, 514));
        jPanelBotones.setLayout(new java.awt.GridLayout(0, 1));
        jPanelPreguntaBotones.add(jPanelBotones);

        jPanel1.add(jPanelPreguntaBotones);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JPanel jPanelPregunta;
    private javax.swing.JPanel jPanelPreguntaBotones;
    // End of variables declaration//GEN-END:variables
}
