/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author alfgonru
 */
public class VistaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicial
     */
    public VistaInicial() {
        try {
//            com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme
            UIManager.setLookAndFeel("com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme");

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(vistaVerdaderoFalsoMuseos.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setFrame();
    }

    private void setFrame() {
        Color color = Color.decode("#f0dab6");

        this.jPanelPrincipal.setBackground(color);
        this.jPanelJuegos.setBackground(new Color(0,0,0,0));
        this.jPanelPuntuacionesRecorrido.setBackground(new Color(0,0,0,0));
        this.jPanelPuntuaciones.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelJuegos = new javax.swing.JPanel();
        jPanelQuien = new javax.swing.JPanel();
        jButtonQuienLoHizo = new javax.swing.JButton();
        jPanelVerdaderoFalsoMuseos = new javax.swing.JPanel();
        jButtonVerdaderoFalsoMuseos = new javax.swing.JButton();
        jPanelGregorioFernandez = new javax.swing.JPanel();
        jButtonGregorioFernandez = new javax.swing.JButton();
        jPanelColocaMapa = new javax.swing.JPanel();
        jButtonColocaMapa = new javax.swing.JButton();
        jPanelPuntuacionesRecorrido = new javax.swing.JPanel();
        jPanelPuntuaciones = new javax.swing.JPanel();
        jButtonPuntuaciones = new javax.swing.JButton();
        jPanelRecorrido = new javax.swing.JPanel();
        jButtonRecorrido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        jPanelPrincipal.setLayout(new javax.swing.BoxLayout(jPanelPrincipal, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelJuegos.setLayout(new java.awt.GridLayout(2, 2, 40, 40));

        jPanelQuien.setLayout(new javax.swing.BoxLayout(jPanelQuien, javax.swing.BoxLayout.LINE_AXIS));

        jButtonQuienLoHizo.setBackground(new java.awt.Color(196, 178, 149));
        jButtonQuienLoHizo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonQuienLoHizo.setText("¿Quién lo hizo?");
        jButtonQuienLoHizo.setBorder(null);
        jButtonQuienLoHizo.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButtonQuienLoHizo.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonQuienLoHizo.setName("quien"); // NOI18N
        jButtonQuienLoHizo.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanelQuien.add(jButtonQuienLoHizo);

        jPanelJuegos.add(jPanelQuien);

        jPanelVerdaderoFalsoMuseos.setLayout(new javax.swing.BoxLayout(jPanelVerdaderoFalsoMuseos, javax.swing.BoxLayout.LINE_AXIS));

        jButtonVerdaderoFalsoMuseos.setBackground(new java.awt.Color(196, 178, 149));
        jButtonVerdaderoFalsoMuseos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonVerdaderoFalsoMuseos.setText("Verdadero/Falso de Museos");
        jButtonVerdaderoFalsoMuseos.setBorder(null);
        jButtonVerdaderoFalsoMuseos.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButtonVerdaderoFalsoMuseos.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonVerdaderoFalsoMuseos.setName("verdadero"); // NOI18N
        jButtonVerdaderoFalsoMuseos.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanelVerdaderoFalsoMuseos.add(jButtonVerdaderoFalsoMuseos);

        jPanelJuegos.add(jPanelVerdaderoFalsoMuseos);

        jPanelGregorioFernandez.setLayout(new javax.swing.BoxLayout(jPanelGregorioFernandez, javax.swing.BoxLayout.LINE_AXIS));

        jButtonGregorioFernandez.setBackground(new java.awt.Color(196, 178, 149));
        jButtonGregorioFernandez.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonGregorioFernandez.setText("Gregorio Fernández.");
        jButtonGregorioFernandez.setBorder(null);
        jButtonGregorioFernandez.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButtonGregorioFernandez.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonGregorioFernandez.setName("gregorio"); // NOI18N
        jButtonGregorioFernandez.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanelGregorioFernandez.add(jButtonGregorioFernandez);

        jPanelJuegos.add(jPanelGregorioFernandez);

        jPanelColocaMapa.setLayout(new javax.swing.BoxLayout(jPanelColocaMapa, javax.swing.BoxLayout.LINE_AXIS));

        jButtonColocaMapa.setBackground(new java.awt.Color(196, 178, 149));
        jButtonColocaMapa.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonColocaMapa.setText("Coloca en el mapa.");
        jButtonColocaMapa.setBorder(null);
        jButtonColocaMapa.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButtonColocaMapa.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonColocaMapa.setName("mapa"); // NOI18N
        jButtonColocaMapa.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jButtonColocaMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColocaMapaActionPerformed(evt);
            }
        });
        jPanelColocaMapa.add(jButtonColocaMapa);

        jPanelJuegos.add(jPanelColocaMapa);

        jPanelPrincipal.add(jPanelJuegos);

        jPanelPuntuacionesRecorrido.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 1, 1, 1));
        jPanelPuntuacionesRecorrido.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanelPuntuacionesRecorrido.setMinimumSize(new java.awt.Dimension(308, 300));
        jPanelPuntuacionesRecorrido.setPreferredSize(new java.awt.Dimension(1108, 300));
        jPanelPuntuacionesRecorrido.setLayout(new java.awt.GridLayout(1, 0));

        jPanelPuntuaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(200, 1, 1, 1));
        jPanelPuntuaciones.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanelPuntuaciones.setMinimumSize(new java.awt.Dimension(153, 300));
        jPanelPuntuaciones.setPreferredSize(new java.awt.Dimension(553, 300));
        jPanelPuntuaciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 1));

        jButtonPuntuaciones.setBackground(new java.awt.Color(196, 178, 149));
        jButtonPuntuaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonPuntuaciones.setText("Puntuaciones");
        jButtonPuntuaciones.setBorder(null);
        jButtonPuntuaciones.setMaximumSize(new java.awt.Dimension(150, 40));
        jButtonPuntuaciones.setMinimumSize(new java.awt.Dimension(150, 40));
        jButtonPuntuaciones.setName("puntuaciones"); // NOI18N
        jButtonPuntuaciones.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanelPuntuaciones.add(jButtonPuntuaciones);

        jPanelPuntuacionesRecorrido.add(jPanelPuntuaciones);

        jPanelRecorrido.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanelRecorrido.setLayout(new javax.swing.BoxLayout(jPanelRecorrido, javax.swing.BoxLayout.LINE_AXIS));

        jButtonRecorrido.setBackground(new java.awt.Color(196, 178, 149));
        jButtonRecorrido.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButtonRecorrido.setText("recorrido");
        jButtonRecorrido.setActionCommand("");
        jButtonRecorrido.setBorder(null);
        jButtonRecorrido.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButtonRecorrido.setMinimumSize(new java.awt.Dimension(30, 30));
        jButtonRecorrido.setName("recorrido"); // NOI18N
        jButtonRecorrido.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanelRecorrido.add(jButtonRecorrido);

        jPanelPuntuacionesRecorrido.add(jPanelRecorrido);

        jPanelPrincipal.add(jPanelPuntuacionesRecorrido);

        getContentPane().add(jPanelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonColocaMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColocaMapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonColocaMapaActionPerformed

    public JButton getjButtonColocaMapa() {
        return jButtonColocaMapa;
    }

    public JButton getjButtonGregorioFernandez() {
        return jButtonGregorioFernandez;
    }

    public JButton getjButtonPuntuaciones() {
        return jButtonPuntuaciones;
    }

    public JButton getjButtonQuienLoHizo() {
        return jButtonQuienLoHizo;
    }

    public JButton getjButtonRecorrido() {
        return jButtonRecorrido;
    }

    public JButton getjButtonVerdaderoFalsoMuseos() {
        return jButtonVerdaderoFalsoMuseos;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonColocaMapa;
    private javax.swing.JButton jButtonGregorioFernandez;
    private javax.swing.JButton jButtonPuntuaciones;
    private javax.swing.JButton jButtonQuienLoHizo;
    private javax.swing.JButton jButtonRecorrido;
    private javax.swing.JButton jButtonVerdaderoFalsoMuseos;
    private javax.swing.JPanel jPanelColocaMapa;
    private javax.swing.JPanel jPanelGregorioFernandez;
    private javax.swing.JPanel jPanelJuegos;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelPuntuaciones;
    private javax.swing.JPanel jPanelPuntuacionesRecorrido;
    private javax.swing.JPanel jPanelQuien;
    private javax.swing.JPanel jPanelRecorrido;
    private javax.swing.JPanel jPanelVerdaderoFalsoMuseos;
    // End of variables declaration//GEN-END:variables
}
