/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Ruben
 */
public class vistaVerdaderoFalsoMuseos extends javax.swing.JFrame {

    /**
     * Creates new form VistaQuienLoHizo
     */
    public vistaVerdaderoFalsoMuseos() {

        try {
//            com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme
            UIManager.setLookAndFeel("com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme");

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(vistaVerdaderoFalsoMuseos.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setFrame();
        System.out.println(jButtonFalso.getBackground().toString());
    }

    private void setFrame() {
        this.setSize(500, 500);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

//        this.jPanel1.setBackground(Color.decode("#1F1F1F"));
//        this.jPanelMuseo.setBackground(new Color(0, 0, 0, 0));
//        this.jPanelPreguntaBotones.setBackground(new Color(0, 0, 0, 0));
//        this.jPanelBotones.setBackground(new Color(0, 0, 0, 0));
//        this.jPanelPregunta.setBackground(new Color(0, 0, 0, 0));
//        this.jButtonFalso.setBackground(new Color(30,30,30, 255));
//        this.jButtonVerdadero.setBackground(new Color(0, 0, 0, 0));
    }

    public JButton getjButtonFalso() {
        return jButtonFalso;
    }

    public void setjButtonFalso(JButton jButtonFalso) {
        this.jButtonFalso = jButtonFalso;
    }

    public JButton getjButtonVerdadero() {
        return jButtonVerdadero;
    }

    public void setjButtonVerdadero(JButton jButtonVerdadero) {
        this.jButtonVerdadero = jButtonVerdadero;
    }

    public JLabel getjLabelMuseo() {
        return jLabelMuseo;
    }

    public void setjLabelMuseo(JLabel jLabelMuseo) {
        this.jLabelMuseo = jLabelMuseo;
    }

    public JLabel getjLabelPregunta() {
        return jLabelPregunta;
    }

    public void setjLabelPregunta(JLabel jLabelPregunta) {
        this.jLabelPregunta = jLabelPregunta;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanelBotones() {
        return jPanelBotones;
    }

    public void setjPanelBotones(JPanel jPanelBotones) {
        this.jPanelBotones = jPanelBotones;
    }

    public JPanel getjPanelMuseo() {
        return jPanelMuseo;
    }

    public void setjPanelMuseo(JPanel jPanelMuseo) {
        this.jPanelMuseo = jPanelMuseo;
    }

    public JPanel getjPanelPregunta() {
        return jPanelPregunta;
    }

    public void setjPanelPregunta(JPanel jPanelPregunta) {
        this.jPanelPregunta = jPanelPregunta;
    }

    public JPanel getjPanelPreguntaBotones() {
        return jPanelPreguntaBotones;
    }

    public void setjPanelPreguntaBotones(JPanel jPanelPreguntaBotones) {
        this.jPanelPreguntaBotones = jPanelPreguntaBotones;
    }

    public JLabel getjLabelPuntuacion() {
        return jLabelPuntuacion;
    }

    public void setjLabelPuntuacion(JLabel jLabelPuntuacion) {
        this.jLabelPuntuacion = jLabelPuntuacion;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPuntuacion = new javax.swing.JLabel();
        jPanelMuseo = new javax.swing.JPanel();
        jLabelMuseo = new javax.swing.JLabel();
        jPanelPreguntaBotones = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jButtonVerdadero = new javax.swing.JButton();
        jButtonFalso = new javax.swing.JButton();
        jPanelPregunta = new javax.swing.JPanel();
        jLabelPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(630, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelPuntuacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPuntuacion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPuntuacion.setText("Puntuación/Obras");
        jPanel2.add(jLabelPuntuacion, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanelMuseo.setMinimumSize(new java.awt.Dimension(300, 150));
        jPanelMuseo.setPreferredSize(new java.awt.Dimension(300, 250));
        jPanelMuseo.setLayout(new java.awt.BorderLayout());

        jLabelMuseo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMuseo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelMuseo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMuseo.setText("Ejemplo");
        jPanelMuseo.add(jLabelMuseo, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelMuseo);

        jPanelPreguntaBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanelPreguntaBotones.setForeground(new java.awt.Color(0, 0, 0));
        jPanelPreguntaBotones.setMaximumSize(new java.awt.Dimension(32769, 250));
        jPanelPreguntaBotones.setMinimumSize(new java.awt.Dimension(330, 64));
        jPanelPreguntaBotones.setPreferredSize(new java.awt.Dimension(330, 250));
        jPanelPreguntaBotones.setLayout(new javax.swing.BoxLayout(jPanelPreguntaBotones, javax.swing.BoxLayout.Y_AXIS));

        jPanelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 50, 0, 50));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jButtonVerdadero.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonVerdadero.setText("Verdadero");
        jPanelBotones.add(jButtonVerdadero);

        jButtonFalso.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonFalso.setText("Falso");
        jPanelBotones.add(jButtonFalso);

        jPanelPreguntaBotones.add(jPanelBotones);

        jPanelPregunta.setLayout(new javax.swing.BoxLayout(jPanelPregunta, javax.swing.BoxLayout.LINE_AXIS));

        jLabelPregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPregunta.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPregunta.setText("¿Crees que el museo es Real o inventado?");
        jPanelPregunta.add(jLabelPregunta);

        jPanelPreguntaBotones.add(jPanelPregunta);

        jPanel1.add(jPanelPreguntaBotones);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(vistaVerdaderoFalsoMuseos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(vistaVerdaderoFalsoMuseos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(vistaVerdaderoFalsoMuseos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(vistaVerdaderoFalsoMuseos.class.getName()).log(Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new vistaVerdaderoFalsoMuseos().setVisible(true);
            }
        }
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFalso;
    private javax.swing.JButton jButtonVerdadero;
    private javax.swing.JLabel jLabelMuseo;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelPuntuacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelMuseo;
    private javax.swing.JPanel jPanelPregunta;
    private javax.swing.JPanel jPanelPreguntaBotones;
    // End of variables declaration//GEN-END:variables
}
