/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Ruben
 */
public class vistaVerdaderoFalsoMuseos extends javax.swing.JFrame {

    /**
     * Creates new form VistaQuienLoHizo
     */
    public vistaVerdaderoFalsoMuseos() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setSize(500, 500);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        this.jPanelMuseo.setBackground(new Color(0, 0, 0, 255));
    }

    public JButton getjButtonFalso() {
        return jButtonFalso;
    }

    public void setjButtonFalso(JButton jButtonFalso) {
        this.jButtonFalso = jButtonFalso;
    }

    public JButton getjButtonVerdadero() {
        return jButtonVerdadero;
    }

    public void setjButtonVerdadero(JButton jButtonVerdadero) {
        this.jButtonVerdadero = jButtonVerdadero;
    }

    public JLabel getjLabelMuseo() {
        return jLabelMuseo;
    }

    public void setjLabelMuseo(JLabel jLabelMuseo) {
        this.jLabelMuseo = jLabelMuseo;
    }

    public JLabel getjLabelPregunta() {
        return jLabelPregunta;
    }

    public void setjLabelPregunta(JLabel jLabelPregunta) {
        this.jLabelPregunta = jLabelPregunta;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanelBotones() {
        return jPanelBotones;
    }

    public void setjPanelBotones(JPanel jPanelBotones) {
        this.jPanelBotones = jPanelBotones;
    }

    public JPanel getjPanelMuseo() {
        return jPanelMuseo;
    }

    public void setjPanelMuseo(JPanel jPanelMuseo) {
        this.jPanelMuseo = jPanelMuseo;
    }

    public JPanel getjPanelPregunta() {
        return jPanelPregunta;
    }

    public void setjPanelPregunta(JPanel jPanelPregunta) {
        this.jPanelPregunta = jPanelPregunta;
    }

    public JPanel getjPanelPreguntaBotones() {
        return jPanelPreguntaBotones;
    }

    public void setjPanelPreguntaBotones(JPanel jPanelPreguntaBotones) {
        this.jPanelPreguntaBotones = jPanelPreguntaBotones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMuseo = new javax.swing.JPanel();
        jLabelMuseo = new javax.swing.JLabel();
        jPanelPreguntaBotones = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jButtonVerdadero = new javax.swing.JButton();
        jButtonFalso = new javax.swing.JButton();
        jPanelPregunta = new javax.swing.JPanel();
        jLabelPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(630, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanelMuseo.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanelMuseo.setPreferredSize(new java.awt.Dimension(300, 350));
        jPanelMuseo.setLayout(new java.awt.BorderLayout());

        jLabelMuseo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelMuseo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelMuseo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelMuseo.add(jLabelMuseo, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelMuseo);

        jPanelPreguntaBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanelPreguntaBotones.setForeground(new java.awt.Color(0, 0, 0));
        jPanelPreguntaBotones.setMinimumSize(new java.awt.Dimension(330, 64));
        jPanelPreguntaBotones.setPreferredSize(new java.awt.Dimension(330, 564));
        jPanelPreguntaBotones.setLayout(new javax.swing.BoxLayout(jPanelPreguntaBotones, javax.swing.BoxLayout.Y_AXIS));

        jPanelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jButtonVerdadero.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonVerdadero.setText("Verdadero");
        jPanelBotones.add(jButtonVerdadero);

        jButtonFalso.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonFalso.setText("Falso");
        jPanelBotones.add(jButtonFalso);

        jPanelPreguntaBotones.add(jPanelBotones);

        jPanelPregunta.setLayout(new javax.swing.BoxLayout(jPanelPregunta, javax.swing.BoxLayout.LINE_AXIS));

        jLabelPregunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPregunta.setText("Selecciona si es falso o verdadero");
        jPanelPregunta.add(jLabelPregunta);

        jPanelPreguntaBotones.add(jPanelPregunta);

        jPanel1.add(jPanelPreguntaBotones);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaVerdaderoFalsoMuseos().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFalso;
    private javax.swing.JButton jButtonVerdadero;
    private javax.swing.JLabel jLabelMuseo;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelMuseo;
    private javax.swing.JPanel jPanelPregunta;
    private javax.swing.JPanel jPanelPreguntaBotones;
    // End of variables declaration//GEN-END:variables
}
