/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Ruben
 */
public class VistaQuienLoHizo extends javax.swing.JFrame {

    /**
     * Creates new form VistaQuienLoHizo
     */
    public VistaQuienLoHizo() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setSize(500, 500);
        this.setVisible(true);
    }

    public JButton getjButtonOp1() {
        return jButtonOp1;
    }

    public void setjButtonOp1(JButton jButtonOp1) {
        this.jButtonOp1 = jButtonOp1;
    }

    public JButton getjButtonOp2() {
        return jButtonOp2;
    }

    public void setjButtonOp2(JButton jButtonOp2) {
        this.jButtonOp2 = jButtonOp2;
    }

    public JButton getjButtonOp3() {
        return jButtonOp3;
    }

    public void setjButtonOp3(JButton jButtonOp3) {
        this.jButtonOp3 = jButtonOp3;
    }

    public JButton getjButtonOp4() {
        return jButtonOp4;
    }

    public void setjButtonOp4(JButton jButtonOp4) {
        this.jButtonOp4 = jButtonOp4;
    }

    public JLabel getjLabelImagen() {
        return jLabelImagen;
    }

    public void setjLabelImagen(JLabel jLabelImagen) {
        this.jLabelImagen = jLabelImagen;
    }

    public JLabel getjLabelPregunta() {
        return jLabelPregunta;
    }

    public void setjLabelPregunta(JLabel jLabelPregunta) {
        this.jLabelPregunta = jLabelPregunta;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanelBotones() {
        return jPanelBotones;
    }

    public void setjPanelBotones(JPanel jPanelBotones) {
        this.jPanelBotones = jPanelBotones;
    }

    public JPanel getjPanelImagen() {
        return jPanelImagen;
    }

    public void setjPanelImagen(JPanel jPanelImagen) {
        this.jPanelImagen = jPanelImagen;
    }

    public JPanel getjPanelPregunta() {
        return jPanelPregunta;
    }

    public void setjPanelPregunta(JPanel jPanelPregunta) {
        this.jPanelPregunta = jPanelPregunta;
    }

    public JPanel getjPanelPreguntaBotones() {
        return jPanelPreguntaBotones;
    }

    public void setjPanelPreguntaBotones(JPanel jPanelPreguntaBotones) {
        this.jPanelPreguntaBotones = jPanelPreguntaBotones;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelImagen = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanelPreguntaBotones = new javax.swing.JPanel();
        jPanelPregunta = new javax.swing.JPanel();
        jLabelPregunta = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jButtonOp1 = new javax.swing.JButton();
        jButtonOp2 = new javax.swing.JButton();
        jButtonOp3 = new javax.swing.JButton();
        jButtonOp4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanelImagen.setMinimumSize(new java.awt.Dimension(300, 500));
        jPanelImagen.setPreferredSize(new java.awt.Dimension(300, 500));
        jPanelImagen.setLayout(new java.awt.BorderLayout());
        jPanelImagen.add(jLabelImagen, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelImagen);

        jPanelPreguntaBotones.setLayout(new javax.swing.BoxLayout(jPanelPreguntaBotones, javax.swing.BoxLayout.Y_AXIS));

        jPanelPregunta.setLayout(new javax.swing.BoxLayout(jPanelPregunta, javax.swing.BoxLayout.LINE_AXIS));

        jLabelPregunta.setText("¿Quien lo hizo?");
        jPanelPregunta.add(jLabelPregunta);

        jPanelPreguntaBotones.add(jPanelPregunta);

        jButtonOp1.setText("1");

        jButtonOp2.setText("2");

        jButtonOp3.setText("3");

        jButtonOp4.setText("4");

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOp4)
                    .addComponent(jButtonOp2)
                    .addComponent(jButtonOp3)
                    .addComponent(jButtonOp1))
                .addGap(117, 117, 117))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButtonOp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOp4)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jPanelPreguntaBotones.add(jPanelBotones);

        jPanel1.add(jPanelPreguntaBotones);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOp1;
    private javax.swing.JButton jButtonOp2;
    private javax.swing.JButton jButtonOp3;
    private javax.swing.JButton jButtonOp4;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JPanel jPanelPregunta;
    private javax.swing.JPanel jPanelPreguntaBotones;
    // End of variables declaration//GEN-END:variables
}
