/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

/**
 *
 * @author alfgonru
 */
public class VistaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicial
     */
    public VistaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelJuegos = new javax.swing.JPanel();
        jPanelQuien = new javax.swing.JPanel();
        jButtonQuienLoHizo = new javax.swing.JButton();
        jPanelVerdaderoFalsoMuseos = new javax.swing.JPanel();
        jButtonVerdaderoFalsoMuseos = new javax.swing.JButton();
        jPanelGregorioFernandez = new javax.swing.JPanel();
        jButtonGregorioFernandez = new javax.swing.JButton();
        jPanelColocaMapa = new javax.swing.JPanel();
        jButtonColocaMapa = new javax.swing.JButton();
        jPanelPuntuacionesRecorrido = new javax.swing.JPanel();
        jPanelPuntuaciones = new javax.swing.JPanel();
        jButtonPuntuaciones = new javax.swing.JButton();
        jPanelRecorrido = new javax.swing.JPanel();
        jButtonRecorrido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        jPanelPrincipal.setLayout(new javax.swing.BoxLayout(jPanelPrincipal, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelJuegos.setLayout(new java.awt.GridLayout(3, 2, 40, 40));

        jPanelQuien.setLayout(new java.awt.BorderLayout());

        jButtonQuienLoHizo.setText("¿Quién lo hizo?");
        jPanelQuien.add(jButtonQuienLoHizo, java.awt.BorderLayout.PAGE_START);

        jPanelJuegos.add(jPanelQuien);

        jPanelVerdaderoFalsoMuseos.setLayout(new java.awt.BorderLayout());

        jButtonVerdaderoFalsoMuseos.setText("Verdadero/Falso de Museos");
        jPanelVerdaderoFalsoMuseos.add(jButtonVerdaderoFalsoMuseos, java.awt.BorderLayout.PAGE_START);

        jPanelJuegos.add(jPanelVerdaderoFalsoMuseos);

        jPanelGregorioFernandez.setLayout(new java.awt.BorderLayout());

        jButtonGregorioFernandez.setText("Gregorio Fernández.");
        jPanelGregorioFernandez.add(jButtonGregorioFernandez, java.awt.BorderLayout.PAGE_END);

        jPanelJuegos.add(jPanelGregorioFernandez);

        jPanelColocaMapa.setLayout(new java.awt.BorderLayout());

        jButtonColocaMapa.setText("Coloca en el mapa.");
        jPanelColocaMapa.add(jButtonColocaMapa, java.awt.BorderLayout.PAGE_END);

        jPanelJuegos.add(jPanelColocaMapa);

        jPanelPrincipal.add(jPanelJuegos);

        jPanelPuntuacionesRecorrido.setLayout(new javax.swing.BoxLayout(jPanelPuntuacionesRecorrido, javax.swing.BoxLayout.LINE_AXIS));

        jPanelPuntuaciones.setLayout(new java.awt.BorderLayout());

        jButtonPuntuaciones.setText("Puntuaciones");
        jPanelPuntuaciones.add(jButtonPuntuaciones, java.awt.BorderLayout.PAGE_END);

        jPanelPuntuacionesRecorrido.add(jPanelPuntuaciones);

        jPanelRecorrido.setLayout(new java.awt.BorderLayout());

        jButtonRecorrido.setText("Recorrido");
        jPanelRecorrido.add(jButtonRecorrido, java.awt.BorderLayout.PAGE_END);

        jPanelPuntuacionesRecorrido.add(jPanelRecorrido);

        jPanelPrincipal.add(jPanelPuntuacionesRecorrido);

        getContentPane().add(jPanelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonColocaMapa;
    private javax.swing.JButton jButtonGregorioFernandez;
    private javax.swing.JButton jButtonPuntuaciones;
    private javax.swing.JButton jButtonQuienLoHizo;
    private javax.swing.JButton jButtonRecorrido;
    private javax.swing.JButton jButtonVerdaderoFalsoMuseos;
    private javax.swing.JPanel jPanelColocaMapa;
    private javax.swing.JPanel jPanelGregorioFernandez;
    private javax.swing.JPanel jPanelJuegos;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelPuntuaciones;
    private javax.swing.JPanel jPanelPuntuacionesRecorrido;
    private javax.swing.JPanel jPanelQuien;
    private javax.swing.JPanel jPanelRecorrido;
    private javax.swing.JPanel jPanelVerdaderoFalsoMuseos;
    // End of variables declaration//GEN-END:variables
}
