/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.vista;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Ruben
 */
public class VistaQuienLoHizo extends javax.swing.JFrame {

    /**
     * Creates new form VistaQuienLoHizo
     */
    public VistaQuienLoHizo() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setSize(900, 500);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        Color color = Color.decode("#f0dab6");

        this.jPanelImagen.setBackground(color);
        this.jPanelPreguntaBotones.setBackground(color);
        this.jPanelPregunta.setBackground(color);
        this.jPanelBotones.setBackground(color);
        this.getjPanel1().setBackground(color);
    }

    public JLabel getjLabelImagen() {
        return jLabelImagen;
    }

    public void setjLabelImagen(JLabel jLabelImagen) {
        this.jLabelImagen = jLabelImagen;
    }

    public JLabel getjLabelPregunta() {
        return jLabelPregunta;
    }

    public void setjLabelPregunta(JLabel jLabelPregunta) {
        this.jLabelPregunta = jLabelPregunta;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanelBotones() {
        return jPanelBotones;
    }

    public void setjPanelBotones(JPanel jPanelBotones) {
        this.jPanelBotones = jPanelBotones;
    }

    public JPanel getjPanelImagen() {
        return jPanelImagen;
    }

    public void setjPanelImagen(JPanel jPanelImagen) {
        this.jPanelImagen = jPanelImagen;
    }

    public JPanel getjPanelPregunta() {
        return jPanelPregunta;
    }

    public void setjPanelPregunta(JPanel jPanelPregunta) {
        this.jPanelPregunta = jPanelPregunta;
    }

    public JPanel getjPanelPreguntaBotones() {
        return jPanelPreguntaBotones;
    }

    public void setjPanelPreguntaBotones(JPanel jPanelPreguntaBotones) {
        this.jPanelPreguntaBotones = jPanelPreguntaBotones;
    }

    public JLabel getjLabelPuntuacion() {
        return jLabelPuntuacion;
    }

    public void setjLabelPuntuacion(JLabel jLabelPuntuacion) {
        this.jLabelPuntuacion = jLabelPuntuacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelImagen = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jPanelPreguntaBotones = new javax.swing.JPanel();
        jPanelPregunta = new javax.swing.JPanel();
        jLabelPregunta = new javax.swing.JLabel();
        jLabelPuntuacion = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 600));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanelImagen.setMinimumSize(new java.awt.Dimension(100, 500));
        jPanelImagen.setPreferredSize(new java.awt.Dimension(100, 500));
        jPanelImagen.setLayout(new java.awt.BorderLayout());

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelImagen.add(jLabelImagen, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelImagen);

        jPanelPreguntaBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        jPanelPreguntaBotones.setForeground(new java.awt.Color(0, 0, 0));
        jPanelPreguntaBotones.setMaximumSize(new java.awt.Dimension(450, 32851));
        jPanelPreguntaBotones.setMinimumSize(new java.awt.Dimension(450, 564));
        jPanelPreguntaBotones.setPreferredSize(new java.awt.Dimension(450, 564));
        jPanelPreguntaBotones.setLayout(new javax.swing.BoxLayout(jPanelPreguntaBotones, javax.swing.BoxLayout.Y_AXIS));

        jPanelPregunta.setMaximumSize(new java.awt.Dimension(2147483647, 64));
        jPanelPregunta.setLayout(new java.awt.BorderLayout());

        jLabelPregunta.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelPregunta.setForeground(new java.awt.Color(85, 85, 85));
        jLabelPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPregunta.setText("¿Quien lo hizo?");
        jPanelPregunta.add(jLabelPregunta, java.awt.BorderLayout.CENTER);

        jLabelPuntuacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPuntuacion.setForeground(new java.awt.Color(128, 128, 128));
        jLabelPuntuacion.setText("0/0");
        jPanelPregunta.add(jLabelPuntuacion, java.awt.BorderLayout.LINE_END);

        jPanelPreguntaBotones.add(jPanelPregunta);

        jPanelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        jPanelBotones.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(250, 450));
        jPanelBotones.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        jPanelPreguntaBotones.add(jPanelBotones);

        jPanel1.add(jPanelPreguntaBotones);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLabel jLabelPuntuacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JPanel jPanelPregunta;
    private javax.swing.JPanel jPanelPreguntaBotones;
    // End of variables declaration//GEN-END:variables
}
